import {
	Button,
	Flex,
	Heading,
	Highlight,
	HStack,
	Image,
	Stack,
	Tag,
	Text,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";

const SectionLink: React.FC<{ section: string }> = ({ section }) => {
	return (
		<Link href={`#${section}`}>
			<Heading
				cursor="pointer"
				size="xl"
				borderWidth={1}
				rounded={12}
				p={5}>
				{section.charAt(0).toUpperCase() + section.slice(1)}
			</Heading>
		</Link>
	);
};

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta
					name="description"
					content="Generated by create-t3-app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Stack h="100vh">
				<Stack mx="auto" spacing={2}>
					<Heading size="4xl" textAlign="center">
						Link Drawer
					</Heading>
					<HStack gap={3} fontSize={"1.5rem"}>
						<SectionLink section="minimal" />
						<SectionLink section="stylish" />
						<SectionLink section="free" />
					</HStack>
				</Stack>
				<Stack p={5}>
					<Stack
						as="section"
						id="minimal"
						p={2}
						backgroundColor={"teal.500"}>
						<Heading>Minimal</Heading>
						<HStack>
							<Stack>
								<Text>
									With a clear and easy-to-use interface,
									you can create a list of links that can
									be shared and embedded with ease.
								</Text>
								<Text>
									With a clear and easy-to-use interface,
									you can create a list of links that can
									be shared and embedded with ease.
								</Text>
							</Stack>
							<Image
								boxSize={"sm"}
								objectFit="cover"
								alt="asdasd"
								src="https://images.unsplash.com/photo-1502759683299-cdcd6974244f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDh8fHxlbnwwfHx8fA%3D%3D&w=1000&q=80"
							/>
						</HStack>
					</Stack>
					<Stack
						as="section"
						id="stylish"
						backgroundColor={"teal.500"}>
						<Heading>Stylish</Heading>
					</Stack>
					<Stack
						as="section"
						id="free"
						backgroundColor={"teal.500"}>
						<Heading>Free</Heading>
					</Stack>
				</Stack>
			</Stack>
		</>
	);
};

export default Home;
